<a href="https://colab.research.google.com/github/nisha-s10/Deep-Learning-Lab-AFI524/blob/main/Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating 1D, 2D, and 3D Tensors using NumPy and PyTorch

In [ ]:
import numpy as np
import torch

# Using NumPy
# 1D Tensor
np_1d = np.array([1, 2, 3])
print("NumPy 1D:", np_1d)

# 2D Tensor
np_2d = np.array([[1, 2], [3, 4]])
print("NumPy 2D:\n", np_2d)

# 3D Tensor
np_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("NumPy 3D:\n", np_3d)

print("--------------------------")

# Using PyTorch
# 1D Tensor
pt_1d = torch.tensor([1, 2, 3])
print("PyTorch 1D:", pt_1d)

# 2D Tensor
pt_2d = torch.tensor([[1, 2], [3, 4]])
print("PyTorch 2D:\n", pt_2d)

# 3D Tensor
pt_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("PyTorch 3D:\n", pt_3d)

NumPy 1D: [1 2 3]
NumPy 2D:
 [[1 2]
 [3 4]]
NumPy 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------------
PyTorch 1D: tensor([1, 2, 3])
PyTorch 2D:
 tensor([[1, 2],
        [3, 4]])
PyTorch 3D:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


# Basic Element-wise Operations

In [ ]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: tensor([12, 24, 35])
Subtraction: tensor([ 8, 16, 25])
Multiplication: tensor([ 20,  80, 150])
Division: tensor([5., 5., 6.])


# Dot Product & Matrix Multiplication

In [ ]:
# Dot Product
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

dot = torch.dot(x, y)
print("Dot Product:", dot)

#Matrix Multiplication
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

dot = torch.dot(x, y)
print("Dot Product:", dot)

Dot Product: tensor(32)
Dot Product: tensor(32)


# Indexing & Slicing

In [ ]:
# Basic Indexing
tensor = torch.tensor([[10, 20, 30],
                       [40, 50, 60]])

print("Element:", tensor[0, 1])
print("Row:", tensor[1])
print("Column:", tensor[:, 2])

# Boolean Masking
mask = tensor > 30
print("Mask:\n", mask)
print("Filtered values:", tensor[mask])

# Extracting Sub-Tensor
sub_tensor = tensor[:, 1:]
print("Sub Tensor:\n", sub_tensor)

Element: tensor(20)
Row: tensor([40, 50, 60])
Column: tensor([30, 60])
Mask:
 tensor([[False, False, False],
        [ True,  True,  True]])
Filtered values: tensor([40, 50, 60])
Sub Tensor:
 tensor([[20, 30],
        [50, 60]])


# Use operations and compare .reshape with numpy .reshape

In [ ]:
t = torch.arange(6)

print("Original:", t)

print("View (2x3):\n", t.view(2, 3))
print("Reshape (3x2):\n", t.reshape(3, 2))

np_arr = np.arange(6)
print("NumPy reshape:\n", np_arr.reshape(3, 2))

t = torch.tensor([1, 2, 3])

print("Original shape:", t.shape, t)

t_unsq = t.unsqueeze(0)
print("After unsqueeze:", t_unsq.shape, t_unsq)

t_sq = t_unsq.squeeze()
print("After squeeze:", t_sq.shape, t_sq)


Original: tensor([0, 1, 2, 3, 4, 5])
View (2x3):
 tensor([[0, 1, 2],
        [3, 4, 5]])
Reshape (3x2):
 tensor([[0, 1],
        [2, 3],
        [4, 5]])
NumPy reshape:
 [[0 1]
 [2 3]
 [4 5]]
Original shape: torch.Size([3]) tensor([1, 2, 3])
After unsqueeze: torch.Size([1, 3]) tensor([[1, 2, 3]])
After squeeze: torch.Size([3]) tensor([1, 2, 3])


# Broadcasting

In [ ]:
import torch

# Tensor of shape (2, 3)
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# Tensor of shape (3,)
B = torch.tensor([10, 20, 30])

# Broadcasting operations
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", A * B)
print("Division:\n", A / B)

Addition:
 tensor([[11, 22, 33],
        [14, 25, 36]])
Subtraction:
 tensor([[ -9, -18, -27],
        [ -6, -15, -24]])
Multiplication:
 tensor([[ 10,  40,  90],
        [ 40, 100, 180]])
Division:
 tensor([[0.1000, 0.1000, 0.1000],
        [0.4000, 0.2500, 0.2000]])


# In-place vs Out-of-place Operations

In [ ]:
# Out-of-place Operation
x = torch.tensor([1, 2, 3])
y = x + 5

print("x:", x)
print("y:", y)

# In place Operation
x = torch.tensor([1, 2, 3])
x.add_(5)

print("In-place x:", x)

x: tensor([1, 2, 3])
y: tensor([6, 7, 8])
In-place x: tensor([6, 7, 8])
